controller_list:
  - name: fake_arm_controller
    joints:
      - base_rotation_joint
      - shoulder_joint
      - elbow1_joint
      - elbow2_joint
      - wrist_joint
  - name: fake_gripper_controller
    joints:
      - wrist_joint
      - left_finger_joint
      - right_finger_joint